[package]
name = "rdf2hdt"
version = "0.4.0"
authors = ["Greg Hanson <g.isaac.hanson@gmail.com>"]
edition = "2024"
license = "BSD-3-Clause"
description = "Library for converting a RDF data to HDT"
repository = "https://github.com/DeciSym/rdf2hdt"
readme = "README.md"
keywords = ["hdt", "rdf", "semantic-web", "converter", "parser"]
categories = ["command-line-utilities", "encoding", "parser-implementations", "science", "web-programming"]

[[bench]]
name = "benchmark"
harness = false

[dependencies]
bzip2 = "0.6"
clap = { version = "4.5", features = ["derive","cargo"] }
clap-verbosity-flag = "3.0"
env_logger = "0.11"
flate2 = "1"
hdt = { version = "0.6", default-features = false, features = ["nt"]}
log = "0.4"
oxrdf = "0.3"
oxrdfio = "0.2"
tempfile = "3.27"
url = "2.5"

[dev-dependencies]
criterion = "0.5"
pprof = { version = "0.15", features = ["protobuf", "protobuf-codec", "criterion"] }
walkdir = "2.5"
