[package]
name = "rdf2hdt"
version = "0.1.1"
authors = ["Greg Hanson <g.isaac.hanson@gmail.com>"]
edition = "2024"
license = "BSD-3-Clause"
description = "Library for converting a RDF data to HDT"
repository = "https://github.com/DeciSym/rdf2hdt"
readme = "README.md"
keywords = ["hdt", "rdf", "semantic-web", "converter", "parser"]
categories = ["command-line-utilities", "encoding", "parser-implementations", "science", "web-programming"]

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5", features = ["derive","cargo"] }
clap-verbosity-flag = "3.0"
crc = "3.2.1"
env_logger = "0.11"
hdt = { git = "https://github.com/KonradHoeffner/hdt/" }
log = "0.4"
oxrdf = "0.2"
oxrdfio = "0.1"
tempfile = "3.19"
