[package]
name = "rdf2hdt"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5", features = ["derive","cargo"] }
clap-verbosity-flag = "3.0"
crc = "3.2.1"
hdt = { git = "https://github.com/GregHanson/hdt/", branch = "more-public-vals" }
log = "0.4"
oxrdf = "0.2"
oxrdfio = "0.1"
tempfile = "3.19"
